#-*- coding: utf-8 -*-
# author : yenos
# descript : static 변수선언.

#년수
MONTH_TO_HOUR = 720 
YEAR_TO_HOUR = 720 * 12 

SYNC_END_TIME_STATE_FORWARD = 1
SYNC_END_TIME_STATE_BACKWARD = 2

#calendarReco
CALENDAR_RECO_STATE_DONE = 2
CALENDAR_RECO_STATE_DO = 1

#로그인 상태관리
LOGIN_STATE_FIRST = 'LOGIN_STATS_SIGNUP'
LOGIN_STATE_AUTO = 'LOGIN_STATE_AUTO'
LOGIN_STATE_OTHERDEVICE = 'LOGIN_STATE_OTHERDEVICE'
LOGIN_STATE_RELOGIN = 'LOGIN_STATE_RELOGIN'

LOGIN_STATE_RESIGNUP = 'LOGIN_STATE_RESIGNUP'

#캘린더 동기화 날짜상태관리
SYNC_TIME_STATE_FORWARD = 'SYNC_TIME_STATE_FORWARD'
SYNC_TIME_STATE_BACKWARD = 'SYNC_TIME_STATE_BACKWARD'



#########유저 lifeSTAT status
#해당 스테이트가 시작할때 설정해준다. 
#모든 상황은 성공했을때 로그로 저장된다.
# 라이프사이클상 순서대로 이루어지지않을 경우 뭔가 문제가 있는 경우이다.
LIFE_STATE_SIGNUP = 'LIFE_STATE_SIGNUP'
LIFE_STATE_SIGNIN_AUTO = 'LIFE_STATE_SIGNIN_AUTO'
LIFE_STATE_SIGNIN_RELOGIN = 'LIFE_STATE_SIGNIN_RELOGIN'
LIFE_STATE_SIGNIN_OTEHRDEVICE = 'LIFE_STATE_SIGNIN_OTEHRDEVICE'

#싱크요청시작할떄
LIFE_STATE_CALDAV_FORWARD_SYNCING = 'LIFE_STATE_CALDAV_FORWARD_SYNCING'
LIFE_STATE_CALDAV_BACKWARD_SYNCING = 'LIFE_STATE_CALDAV_BACKWARD_SYNCING'

#싱크요청 끝났을때
LIFE_STATE_CALDAV_FORWARD_SYNC_END = 'LIFE_STATE_CALDAV_FORWARD_SYNC_END'
LIFE_STATE_CALDAV_BACKWARD_SYNC_END = 'LIFE_STATE_CALDAV_BACKWARD_SYNC_END'


#구글
LIFE_STATE_GOOGLE_FORWARD_SYNCING = 'LIFE_STATE_GOOGLE_FORWARD_SYNCING'
LIFE_STATE_GOOGLE_BACKWARD_SYNCING = 'LIFE_STATE_GOOGLE_BACKWARD_SYNCING'

LIFE_STATE_GOOGLE_FORWARD_SYNC_END = 'LIFE_STATE_GOOGLE_FORWARD_SYNC_END'
LIFE_STATE_GOOGLE_BACKWARD_SYNC_END = 'LIFE_STATE_GOOGLE_BACKWARD_SYNC_END'

LIFE_STATE_GOOGLE_PUSH_END = 'LIFE_STATE_GOOGLE_PUSH_END'
#addAccount요청 보냈을때
LIFE_STATE_ADDACCOUNT = 'LIFE_STATE_ADDACCOUNT'
LIFE_STATE_ADDACCOUNT_END = 'LIFE_STATE_ADDACCOUNT_END'

#recoing은 sync_end일경우 바로 같은 상황이된다.
# LIFE_STATE_RECOING = 'LIFE_STATE_RECOING'
#유저에게 추천 끝났다고 요청보냈을때 설정한다.
LIFE_STATE_RECOEND = 'LIFE_STATE_RECOEND'
#등록했을경우
LIFE_STATE_REGISTER_DEVICE = 'LIFE_STATE_REGISTER_DEVICE'
#유저가 로그아웃 했을경우
LIFE_STATE_LOGOUT = 'LIFE_STATE_LOGOUT'
#유저가 탈퇴했을 경우
LIFE_STATE_WITHDRAWAL = 'LIFE_STATE_WITHDRAWAL'
#에러가 나왔을경우
LIFE_STATE_ERROR = 'LIFE_STATE_ERROR'





#로그인 에러상황
LOGIN_ERROR_INVALID = 'inValid apikey!'
LOGIN_ERROR = 'LOGIN_ERROR'

#캘린더 완료 일경우.
GOOGLE_SYNC_STATE_EVENTS_END = 1
GOOGLE_SYNC_STATE_PUSH_START = 2
GOOGLE_SYNC_STATE_PUSH_END = 3
# GOOLGE_PUSH_SYNC_END = 3

#구글 만기 예정 safe time
EXPIRE_SAFE_RANGE = 180

 
#일정 리스트 보여줄 갯수
EVENTS_FORWARD_CNT = 6
EVENTS_BACKWARD_CNT = 6
EVENTS_ITEM_CNT = 6

#타입 넘버
#일반 문의
REQUESTS_TYPE_DEFAULT = 0
#회원탈퇴
REQUESTS_TYPE_WITHDRAWAL = 1

#싱크 이넘관리
SYNC_CALDAV_SUCCESS = "SYNC_STATE_CALDAV_SUCCES"
SYNC_CALDAV_ERR_SET_CALENDAR = "SYNC_STATE_CALDAV_ERR_SET_CALENDAR"
SYNC_CALDAV_ERR_SET_EVENTS = "SYNC_STATE_CALDAV_ERR_SET_EVENTS"
SYNC_CALDAV_ERR_SET_SYNC_TIME = "SYNC_STATE_CALDAV_ERR_SET_SYNC_TIME"
SYNC_CALDAV_ERR_SET_SYNC_END = "SYNC_CALDAV_ERR_SET_SYNC_END"
SYNC_CALDAV_ERR_ALREADY_REIGITER = "SYNC_CALDAV_ERR_SET_SYNC_END"



SYNC_GOOGLE_SUCCES = "SYNC_GOOGLE_SUCCES"
SYNC_GOOGLE_ERR_SET_CALENDAR = "SYNC_GOOGLE_ERR_SET_CALENDAR"



#응담 메시지들
MSG_LOGIN_AUTO = 'auto login success'
MSG_LOGIN_SIGNUP = 'first sign up'
MSG_LOGIN_COMPLUSION_UPDATE = 'need compulsion update'

#sync
MSG_SYNC_ALREADY = 'sync already end'

MSG_INVALID_TOKENKEY = 'invalid token key'
#EVENT 없을경우
MSG_EVENTS_END = 'event data end'
#추천 없을경우
MSG_RECO_END = 'reco data end'
#그냥 없어
MSG_DATA_NONE = 'data none'
MSG_RECO_SUCCESS = 'recomendation ends'
MSG_RECO_ING = 'recomendation ing'

MSG_SUCCESS_ADD_ACCOUNT = 'success add account'
MSG_FAILE_ADD_ACCOUNT_REGISTERD = 'already registerd'
MSG_LOGOUT_SUCCESS = 'log out success'
MSG_WITHDRAWL_SUCCESS = 'withdrawl success'

#구글 아직 로딩중. 정확한 결과는 푸시
MSG_SUCCESS_GOOLE_SYNC_LOADING = 'success sync loading'
#캘대브 성공
MSG_SUCCESS_CALDAV_SYNC = 'Caldav Sync Success'

#
MSG_SUCCESS = 'success'




