##redis Session key
SESSION_KEY = 'SESSION_KEY'

LOGIN_STATE_FIRST = 'LOGIN_STATS_SIGNUP'
LOGIN_STATE_AUTO = 'LOGIN_STATE_AUTO'
LOGIN_STATE_OTHERDEVICE = 'LOGIN_STATE_OTHERDEVICE'
LOGIN_STATE_RELOGIN = 'LOGIN_STATE_RELOGIN'


LOGIN_ERROR_INVALID = 'inValid sessionkey!'
LOGIN_ERROR = 'LOGIN_ERROR'

CALENDAR_SYNC = 2

 